name: upanzi_kash
description: "Record Keeper for Youth Farmers in Kenya - A mobile-first, offline-enabled app to empower young Kenyan farmers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  flutterfire_cli: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
