// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINTphFbBK5Sedcj4YNXHQP8HxwAroc-A',
    appId: '1:45548092281:web:aa31adea1cceb26f9f0da8',
    messagingSenderId: '45548092281',
    projectId: 'upanzikash-app',
    authDomain: 'upanzikash-app.firebaseapp.com',
    storageBucket: 'upanzikash-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkamPtv5gqVMivOJPZXDTz9BGwFVlH_2A',
    appId: '1:45548092281:android:9ad55e3819fe0ad89f0da8',
    messagingSenderId: '45548092281',
    projectId: 'upanzikash-app',
    storageBucket: 'upanzikash-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrsrjw1DLIAj4FjzXiqA4h5pqRuPTLZg',
    appId: '1:45548092281:ios:72774d46df04605d9f0da8',
    messagingSenderId: '45548092281',
    projectId: 'upanzikash-app',
    storageBucket: 'upanzikash-app.appspot.com',
    iosBundleId: 'com.example.upanziKash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzrsrjw1DLIAj4FjzXiqA4h5pqRuPTLZg',
    appId: '1:45548092281:ios:72774d46df04605d9f0da8',
    messagingSenderId: '45548092281',
    projectId: 'upanzikash-app',
    storageBucket: 'upanzikash-app.appspot.com',
    iosBundleId: 'com.example.upanziKash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBINTphFbBK5Sedcj4YNXHQP8HxwAroc-A',
    appId: '1:45548092281:web:04ca1ca6b2fbc8c49f0da8',
    messagingSenderId: '45548092281',
    projectId: 'upanzikash-app',
    authDomain: 'upanzikash-app.firebaseapp.com',
    storageBucket: 'upanzikash-app.appspot.com',
  );
}
